### ISSUE TITLE
code release?

### ISSUE THREAD

**Issue by Nusselder9** [StiphyJay/LiDAR-PTQ#1]
Congratuation on acceptance. Any plan to release code? thks!

**Comment by StiphyJay** [comment]
Thanks for your interest. I am currently working on deploying the code for the KITTI dataset. Due to the large size of the nuScenes and Waymo datasets, it is not convenient for researchers to test them fastly. I expect to release the code within 1-2 weeks.

**Comment by Siyeong-Lee** [comment]
Have your code release plans been delayed?

**Comment by StiphyJay** [comment]
> Have your code release plans been delayed?

Sorry for the potential delay in this open-source project. Recently, I have been preparing for my doctoral proposal, which has required my attention. However, I have been actively organizing the experimental results on the KITTI dataset.

**Comment by Siyeong-Lee** [comment]
Thank you for fast reply! Good luck for your doctoral defence!
